my_array = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
print(my_array)
my_array.clear()
print(my_array)
my_array.append(5)
print(my_array)
dir(my_array)
print(my_array)
my_array.insert(1, 2)
print(my_array)
my_array.count(2)
print(my_array)
my_array.reverse()
print(my_array)
